[package]
name = "point-framer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.8.1"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
geo = "0.23.0"
geo-types = "0.7.7"
